import type {
  URL,
  Email,
  People,
  Dependencies
} from './utils'

import type {
  Name,
  Keywords,
  Bugs,
  Contributors,
  FundingFund,
  Funding,
  Files,
  Browser,
  Bin,
  Man,
  Directories as OfficialDirectories,
  Repository,
  PreScripts,
  RunScripts as OfficialRunScripts,
  PostScripts,
  Scripts as OfficialScripts,
  Config,
  PeerDependenciesMeta,
  BundleDependencies,
  Overrides,
  Engines as OfficialEngines,
  OS,
  CPU,
  Private,
  PublishConfigAccess,
  PublishConfig,
  Workspaces
} from './OfficialPackage'
import type OfficialPackage from './OfficialPackage'

import type {
  ActivationEvents,
  API,
  AVAEnvironmentVariables,
  AVAExtensions,
  AVAFiles,
  AVAIgnoredByWatcher,
  AVAMatch,
  AVANodeArguments,
  AVARequire,
  AVATimeout,
  AVATypeScriptCompile,
  AVATypeScriptExtensions,
  AVATypeScriptRewritePaths,
  AVATypeScript,
  AVA,
  Badges,
  BundledDependencies,
  CapabilitiesUntrustedWorkspacesSupported,
  CapabilitiesUntrustedWorkspacesRestrictedConfigurations,
  CapabilitiesUntrustedWorkspaces,
  CapabilitiesVirtualWorkspacesSupported,
  CapabilitiesVirtualWorkspaces,
  Capabilities,
  Categories,
  Contributes,
  Directories as UnofficialDirectories,
  Dist,
  EnabledApiProposals,
  Engines as UnofficialEngines,
  ESLintConfigECMAFeatures,
  ESLintConfigENV,
  ESLintConfigExtends,
  ESLintConfigGlobals,
  ESLintConfigIgnorePatterns,
  ESLintConfigOverrides,
  ESLintConfigParserOptionsECMAFeatures,
  ESLintConfigParserOptionsECMAVersion,
  ESLintConfigParserOptionsSourceType,
  ESLintConfigParserOptions,
  ESLintConfigPlugins,
  ESLintConfigRules,
  ESLintConfigSettings,
  ESLintConfig,
  ESNext,
  Exports,
  ExtensionDependencies,
  ExtensionKind,
  ExtensionPack,
  GalleryBannerTheme,
  GalleryBanner,
  Icon,
  JSCPDFormat,
  JSCPDFormatsExts,
  JSCPDIgnore,
  JSCPDIgnorePattern,
  JSCPDMaxSize,
  JSCPDMode,
  JSCPDOutput,
  JSCPDPath,
  JSCPDReporters,
  JSCPDReportersOptionsBadgeColor,
  JSCPDReportersOptionsBadgeLabelColor,
  JSCPDReportersOptionsBadgeStyle,
  JSCPDReportersOptionsBadge,
  JSCPDReportersOptions,
  JSCPDStore,
  JSCPD,
  JSPM,
  Licenses,
  Maintainers,
  Markdown,
  PackageManager,
  Prettier,
  QnA,
  ReleaseBranches,
  ReleaseExtends,
  ReleasePlugins,
  Release,
  Resolutions,
  RunScripts as UnofficialRunScripts,
  Scripts as UnofficialScripts,
  Sponsor,
  StylelintSeverity,
  StylelintExtends,
  StylelintIgnoreFiles,
  StylelintRules,
  StylelintOverrides,
  StylelintPlugins,
  StylelintProcessors,
  StylelintRuleObject,
  StylelintReport,
  Stylelint,
  Type,
  TypesVersions
} from './UnofficialPackage'
import type UnofficialPackage from './UnofficialPackage'

import type BasePackage from './BasePackage'

import type Package from './Package'

export type {
  // utils
  URL,
  Email,
  People,
  Dependencies,
  // official
  Name,
  Keywords,
  Bugs,
  Contributors,
  FundingFund,
  Funding,
  Files,
  Browser,
  Bin,
  Man,
  OfficialDirectories,
  Repository,
  PreScripts,
  OfficialRunScripts,
  PostScripts,
  OfficialScripts,
  Config,
  PeerDependenciesMeta,
  BundleDependencies,
  Overrides,
  OfficialEngines,
  OS,
  CPU,
  Private,
  PublishConfigAccess,
  PublishConfig,
  Workspaces,
  OfficialPackage,
  // unofficial
  ActivationEvents,
  API,
  AVAEnvironmentVariables,
  AVAExtensions,
  AVAFiles,
  AVAIgnoredByWatcher,
  AVAMatch,
  AVANodeArguments,
  AVARequire,
  AVATimeout,
  AVATypeScriptCompile,
  AVATypeScriptExtensions,
  AVATypeScriptRewritePaths,
  AVATypeScript,
  AVA,
  Badges,
  BundledDependencies,
  CapabilitiesUntrustedWorkspacesSupported,
  CapabilitiesUntrustedWorkspacesRestrictedConfigurations,
  CapabilitiesUntrustedWorkspaces,
  CapabilitiesVirtualWorkspacesSupported,
  CapabilitiesVirtualWorkspaces,
  Capabilities,
  Categories,
  Contributes,
  UnofficialDirectories,
  Dist,
  EnabledApiProposals,
  UnofficialEngines,
  ESLintConfigECMAFeatures,
  ESLintConfigENV,
  ESLintConfigExtends,
  ESLintConfigGlobals,
  ESLintConfigIgnorePatterns,
  ESLintConfigOverrides,
  ESLintConfigParserOptionsECMAFeatures,
  ESLintConfigParserOptionsECMAVersion,
  ESLintConfigParserOptionsSourceType,
  ESLintConfigParserOptions,
  ESLintConfigPlugins,
  ESLintConfigRules,
  ESLintConfigSettings,
  ESLintConfig,
  ESNext,
  Exports,
  ExtensionDependencies,
  ExtensionKind,
  ExtensionPack,
  GalleryBannerTheme,
  GalleryBanner,
  Icon,
  JSCPDFormat,
  JSCPDFormatsExts,
  JSCPDIgnore,
  JSCPDIgnorePattern,
  JSCPDMaxSize,
  JSCPDMode,
  JSCPDOutput,
  JSCPDPath,
  JSCPDReporters,
  JSCPDReportersOptionsBadgeColor,
  JSCPDReportersOptionsBadgeLabelColor,
  JSCPDReportersOptionsBadgeStyle,
  JSCPDReportersOptionsBadge,
  JSCPDReportersOptions,
  JSCPDStore,
  JSCPD,
  JSPM,
  Licenses,
  Maintainers,
  Markdown,
  PackageManager,
  Prettier,
  QnA,
  ReleaseBranches,
  ReleaseExtends,
  ReleasePlugins,
  Release,
  Resolutions,
  UnofficialRunScripts,
  UnofficialScripts,
  Sponsor,
  StylelintSeverity,
  StylelintExtends,
  StylelintIgnoreFiles,
  StylelintRules,
  StylelintOverrides,
  StylelintPlugins,
  StylelintProcessors,
  StylelintRuleObject,
  StylelintReport,
  Stylelint,
  Type,
  TypesVersions,
  UnofficialPackage,
  // base
  BasePackage,
  // default
  Package
}

export default Package
